# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c384536855b6cb9214e323db5f153197a175a7817cdd73b4fc166d615f617d57802cc2286534d559994f476052152bacdbdfc9f364f5b8956435a6b676ebf765

test:
  secret_key_base: 95ab930f66f985ef9481b935ce5b4689d59edc2f67fb682ab75d66961fd93d9d4fab69957d8031d5508a8a4cb2f781f84ca5853fd4816289673670eef0f019b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
